revert most of r60663, apparently committed by accident; this repeat_umount stuff is no longer needed
r60664

diff --git a/linux-boot-prober b/linux-boot-prober
--- a/linux-boot-prober
+++ b/linux-boot-prober
@@ -46,7 +46,9 @@ else
 			fi
 		done
 		if [ "$bootmounted" = 1 ]; then
-			repeat_umount "$mpoint/boot" || true
+			if ! umount "$mpoint/boot"; then
+				warn "failed to umount $mpoint/boot"
+			fi
 		fi
 	fi
 fi
diff --git a/linux-boot-probes/common/50mounted-tests b/linux-boot-probes/common/50mounted-tests
--- a/linux-boot-probes/common/50mounted-tests
+++ b/linux-boot-probes/common/50mounted-tests
@@ -21,16 +21,20 @@ for type in $(grep -v nodev /proc/filesystems); do
 				debug "running $test $partition $bootpart $tmpmnt $type"
 				if $test "$partition" "$bootpart" "$tmpmnt" "$type"; then
 					debug "$test succeeded"
-					repeat_umount $tmpmnt/boot 2>/dev/null || true 	
-					repeat_umount $tmpmnt
+					umount $tmpmnt/boot 2>/dev/null || true 	
+					if ! umount $tmpmnt; then
+						warn "failed to umount $tmpmnt"
+					fi
 					rmdir $tmpmnt || true
 					exit 0
 				fi
 			fi
 		done
 		
-		repeat_umount $tmpmnt/boot 2>/dev/null || true 	
-		repeat_umount $tmpmnt
+		umount $tmpmnt/boot 2>/dev/null || true 	
+		if ! umount $tmpmnt; then
+			warn "failed to umount $tmpmnt"
+		fi
 
 		break
 	fi
