Improve error message when /sys/block is missing.
r64834

diff --git a/os-prober b/os-prober
--- a/os-prober
+++ b/os-prober
@@ -49,7 +49,7 @@ partitions () {
 			done
 		fi
 	else
-		echo "Cannot find list of partitions!" >&2
+		echo "Cannot find list of partitions!  (Try mounting /sys.)" >&2
 		exit 1
 	fi
 
