* Warn if umount fails for some reason (such as a desktop environment   keeping the mount point busy). * Avoid exiting test scripts when a umount fails, as that can result in   incomplete OS detection, and does not result in os-prober as a whole   failing.
r52681

diff --git a/linux-boot-probes/common/50mounted-tests b/linux-boot-probes/common/50mounted-tests
--- a/linux-boot-probes/common/50mounted-tests
+++ b/linux-boot-probes/common/50mounted-tests
@@ -22,7 +22,9 @@ for type in $(grep -v nodev /proc/filesystems); do
 				if $test $partition $bootpart $tmpmnt $type; then
 					debug "$test succeeded"
 					umount $tmpmnt/boot 2>/dev/null || true 	
-					umount $tmpmnt
+					if ! umount $tmpmnt; then
+						warn "failed to umount $tmpmnt"
+					fi
 					rmdir $tmpmnt || true
 					exit 0
 				fi
@@ -30,7 +32,9 @@ for type in $(grep -v nodev /proc/filesystems); do
 		done
 		
 		umount $tmpmnt/boot 2>/dev/null || true 	
-		umount $tmpmnt
+		if ! umount $tmpmnt; then
+			warn "failed to umount $tmpmnt"
+		fi
 
 		break
 	fi
diff --git a/os-probes/common/50mounted-tests b/os-probes/common/50mounted-tests
--- a/os-probes/common/50mounted-tests
+++ b/os-probes/common/50mounted-tests
@@ -32,13 +32,17 @@ for type in $types $delaytypes; do
 			if [ -f $test ] && [ -x $test ]; then
 				if $test $partition $tmpmnt $type; then
 					debug "os found by subtest $test"
-					umount $tmpmnt
+					if ! umount $tmpmnt; then
+						warn "failed to umount $tmpmnt"
+					fi
 					rmdir $tmpmnt || true
 					exit 0
 				fi
 			fi
 		done
-		umount $tmpmnt
+		if ! umount $tmpmnt; then
+			warn "failed to umount $tmpmnt"
+		fi
 		break
 	fi
 done
